INSERT INTO CATALOG (PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
VALUES('CATALOG-0001', 'BERLIN', 100, 1500);

INSERT INTO CATALOG (PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
VALUES('CATALOG-0002', 'TOKYO', 110, 780);

INSERT INTO CATALOG (PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
VALUES('CATALOG-0003', 'KOREA', 130, 1900);
